//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdi3_23.Cli_SOAPcsharp.ServiceReference1 {
    
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
    public partial class BusinessException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string claveFicheroMensajesField;
        
        private string messageField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string claveFicheroMensajes {
            get {
                return this.claveFicheroMensajesField;
            }
            set {
                this.claveFicheroMensajesField = value;
                this.RaisePropertyChanged("claveFicheroMensajes");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://impl.business.sdi.uo/", ConfigurationName="ServiceReference1.AdminService_SOAP")]
    public interface AdminService_SOAP {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(sdi3_23.Cli_SOAPcsharp.ServiceReference1.BusinessException), Action="", Name="BusinessException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void restartDatabase();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task restartDatabaseAsync();
        
        // CODEGEN: El parámetro 'arg0' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(sdi3_23.Cli_SOAPcsharp.ServiceReference1.BusinessException), Action="", Name="BusinessException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        sdi3_23.Cli_SOAPcsharp.ServiceReference1.deepDeleteUserResponse deepDeleteUser(sdi3_23.Cli_SOAPcsharp.ServiceReference1.deepDeleteUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<sdi3_23.Cli_SOAPcsharp.ServiceReference1.deepDeleteUserResponse> deepDeleteUserAsync(sdi3_23.Cli_SOAPcsharp.ServiceReference1.deepDeleteUser request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(sdi3_23.Cli_SOAPcsharp.ServiceReference1.BusinessException), Action="", Name="BusinessException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        sdi3_23.Cli_SOAPcsharp.ServiceReference1.findAllUsersInfoResponse findAllUsersInfo(sdi3_23.Cli_SOAPcsharp.ServiceReference1.findAllUsersInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<sdi3_23.Cli_SOAPcsharp.ServiceReference1.findAllUsersInfoResponse> findAllUsersInfoAsync(sdi3_23.Cli_SOAPcsharp.ServiceReference1.findAllUsersInfo request);
        
        // CODEGEN: El parámetro 'arg0' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(sdi3_23.Cli_SOAPcsharp.ServiceReference1.BusinessException), Action="", Name="BusinessException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        sdi3_23.Cli_SOAPcsharp.ServiceReference1.disableUserResponse disableUser(sdi3_23.Cli_SOAPcsharp.ServiceReference1.disableUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<sdi3_23.Cli_SOAPcsharp.ServiceReference1.disableUserResponse> disableUserAsync(sdi3_23.Cli_SOAPcsharp.ServiceReference1.disableUser request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(sdi3_23.Cli_SOAPcsharp.ServiceReference1.BusinessException), Action="", Name="BusinessException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        sdi3_23.Cli_SOAPcsharp.ServiceReference1.findAllUsersResponse findAllUsers(sdi3_23.Cli_SOAPcsharp.ServiceReference1.findAllUsers request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<sdi3_23.Cli_SOAPcsharp.ServiceReference1.findAllUsersResponse> findAllUsersAsync(sdi3_23.Cli_SOAPcsharp.ServiceReference1.findAllUsers request);
        
        // CODEGEN: El parámetro 'arg0' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(sdi3_23.Cli_SOAPcsharp.ServiceReference1.BusinessException), Action="", Name="BusinessException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        sdi3_23.Cli_SOAPcsharp.ServiceReference1.enableUserResponse enableUser(sdi3_23.Cli_SOAPcsharp.ServiceReference1.enableUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<sdi3_23.Cli_SOAPcsharp.ServiceReference1.enableUserResponse> enableUserAsync(sdi3_23.Cli_SOAPcsharp.ServiceReference1.enableUser request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(sdi3_23.Cli_SOAPcsharp.ServiceReference1.BusinessException), Action="", Name="BusinessException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        sdi3_23.Cli_SOAPcsharp.ServiceReference1.findUserByIdResponse findUserById(sdi3_23.Cli_SOAPcsharp.ServiceReference1.findUserById request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<sdi3_23.Cli_SOAPcsharp.ServiceReference1.findUserByIdResponse> findUserByIdAsync(sdi3_23.Cli_SOAPcsharp.ServiceReference1.findUserById request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deepDeleteUser", WrapperNamespace="http://impl.business.sdi.uo/", IsWrapped=true)]
    public partial class deepDeleteUser {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.business.sdi.uo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public deepDeleteUser() {
        }
        
        public deepDeleteUser(long arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deepDeleteUserResponse", WrapperNamespace="http://impl.business.sdi.uo/", IsWrapped=true)]
    public partial class deepDeleteUserResponse {
        
        public deepDeleteUserResponse() {
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
    public partial class userInfoDTO : userDTO {
        
        private long num_finished_delayed_tasksField;
        
        private long num_finished_tasksField;
        
        private long num_not_planned_tasksField;
        
        private long num_planned_tasksField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long num_finished_delayed_tasks {
            get {
                return this.num_finished_delayed_tasksField;
            }
            set {
                this.num_finished_delayed_tasksField = value;
                this.RaisePropertyChanged("num_finished_delayed_tasks");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long num_finished_tasks {
            get {
                return this.num_finished_tasksField;
            }
            set {
                this.num_finished_tasksField = value;
                this.RaisePropertyChanged("num_finished_tasks");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long num_not_planned_tasks {
            get {
                return this.num_not_planned_tasksField;
            }
            set {
                this.num_not_planned_tasksField = value;
                this.RaisePropertyChanged("num_not_planned_tasks");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long num_planned_tasks {
            get {
                return this.num_planned_tasksField;
            }
            set {
                this.num_planned_tasksField = value;
                this.RaisePropertyChanged("num_planned_tasks");
            }
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(userInfoDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
    public partial class userDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string emailField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private bool is_adminField;
        
        private string loginField;
        
        private string passwordField;
        
        private userStatusDTO statusField;
        
        private bool statusFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool is_admin {
            get {
                return this.is_adminField;
            }
            set {
                this.is_adminField = value;
                this.RaisePropertyChanged("is_admin");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("login");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public userStatusDTO status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
    public enum userStatusDTO {
        
        /// <comentarios/>
        ENABLED,
        
        /// <comentarios/>
        DISABLED,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllUsersInfo", WrapperNamespace="http://impl.business.sdi.uo/", IsWrapped=true)]
    public partial class findAllUsersInfo {
        
        public findAllUsersInfo() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllUsersInfoResponse", WrapperNamespace="http://impl.business.sdi.uo/", IsWrapped=true)]
    public partial class findAllUsersInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.business.sdi.uo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sdi3_23.Cli_SOAPcsharp.ServiceReference1.userInfoDTO[] @return;
        
        public findAllUsersInfoResponse() {
        }
        
        public findAllUsersInfoResponse(sdi3_23.Cli_SOAPcsharp.ServiceReference1.userInfoDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="disableUser", WrapperNamespace="http://impl.business.sdi.uo/", IsWrapped=true)]
    public partial class disableUser {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.business.sdi.uo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public disableUser() {
        }
        
        public disableUser(long arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="disableUserResponse", WrapperNamespace="http://impl.business.sdi.uo/", IsWrapped=true)]
    public partial class disableUserResponse {
        
        public disableUserResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllUsers", WrapperNamespace="http://impl.business.sdi.uo/", IsWrapped=true)]
    public partial class findAllUsers {
        
        public findAllUsers() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllUsersResponse", WrapperNamespace="http://impl.business.sdi.uo/", IsWrapped=true)]
    public partial class findAllUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.business.sdi.uo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sdi3_23.Cli_SOAPcsharp.ServiceReference1.userDTO[] @return;
        
        public findAllUsersResponse() {
        }
        
        public findAllUsersResponse(sdi3_23.Cli_SOAPcsharp.ServiceReference1.userDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enableUser", WrapperNamespace="http://impl.business.sdi.uo/", IsWrapped=true)]
    public partial class enableUser {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.business.sdi.uo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public enableUser() {
        }
        
        public enableUser(long arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enableUserResponse", WrapperNamespace="http://impl.business.sdi.uo/", IsWrapped=true)]
    public partial class enableUserResponse {
        
        public enableUserResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findUserById", WrapperNamespace="http://impl.business.sdi.uo/", IsWrapped=true)]
    public partial class findUserById {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.business.sdi.uo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public findUserById() {
        }
        
        public findUserById(long arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findUserByIdResponse", WrapperNamespace="http://impl.business.sdi.uo/", IsWrapped=true)]
    public partial class findUserByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.business.sdi.uo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sdi3_23.Cli_SOAPcsharp.ServiceReference1.userDTO @return;
        
        public findUserByIdResponse() {
        }
        
        public findUserByIdResponse(sdi3_23.Cli_SOAPcsharp.ServiceReference1.userDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AdminService_SOAPChannel : sdi3_23.Cli_SOAPcsharp.ServiceReference1.AdminService_SOAP, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminService_SOAPClient : System.ServiceModel.ClientBase<sdi3_23.Cli_SOAPcsharp.ServiceReference1.AdminService_SOAP>, sdi3_23.Cli_SOAPcsharp.ServiceReference1.AdminService_SOAP {
        
        public AdminService_SOAPClient() {
        }
        
        public AdminService_SOAPClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminService_SOAPClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminService_SOAPClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminService_SOAPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void restartDatabase() {
            base.Channel.restartDatabase();
        }
        
        public System.Threading.Tasks.Task restartDatabaseAsync() {
            return base.Channel.restartDatabaseAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sdi3_23.Cli_SOAPcsharp.ServiceReference1.deepDeleteUserResponse sdi3_23.Cli_SOAPcsharp.ServiceReference1.AdminService_SOAP.deepDeleteUser(sdi3_23.Cli_SOAPcsharp.ServiceReference1.deepDeleteUser request) {
            return base.Channel.deepDeleteUser(request);
        }
        
        public void deepDeleteUser(long arg0) {
            sdi3_23.Cli_SOAPcsharp.ServiceReference1.deepDeleteUser inValue = new sdi3_23.Cli_SOAPcsharp.ServiceReference1.deepDeleteUser();
            inValue.arg0 = arg0;
            sdi3_23.Cli_SOAPcsharp.ServiceReference1.deepDeleteUserResponse retVal = ((sdi3_23.Cli_SOAPcsharp.ServiceReference1.AdminService_SOAP)(this)).deepDeleteUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sdi3_23.Cli_SOAPcsharp.ServiceReference1.deepDeleteUserResponse> sdi3_23.Cli_SOAPcsharp.ServiceReference1.AdminService_SOAP.deepDeleteUserAsync(sdi3_23.Cli_SOAPcsharp.ServiceReference1.deepDeleteUser request) {
            return base.Channel.deepDeleteUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<sdi3_23.Cli_SOAPcsharp.ServiceReference1.deepDeleteUserResponse> deepDeleteUserAsync(long arg0) {
            sdi3_23.Cli_SOAPcsharp.ServiceReference1.deepDeleteUser inValue = new sdi3_23.Cli_SOAPcsharp.ServiceReference1.deepDeleteUser();
            inValue.arg0 = arg0;
            return ((sdi3_23.Cli_SOAPcsharp.ServiceReference1.AdminService_SOAP)(this)).deepDeleteUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sdi3_23.Cli_SOAPcsharp.ServiceReference1.findAllUsersInfoResponse sdi3_23.Cli_SOAPcsharp.ServiceReference1.AdminService_SOAP.findAllUsersInfo(sdi3_23.Cli_SOAPcsharp.ServiceReference1.findAllUsersInfo request) {
            return base.Channel.findAllUsersInfo(request);
        }
        
        public sdi3_23.Cli_SOAPcsharp.ServiceReference1.userInfoDTO[] findAllUsersInfo() {
            sdi3_23.Cli_SOAPcsharp.ServiceReference1.findAllUsersInfo inValue = new sdi3_23.Cli_SOAPcsharp.ServiceReference1.findAllUsersInfo();
            sdi3_23.Cli_SOAPcsharp.ServiceReference1.findAllUsersInfoResponse retVal = ((sdi3_23.Cli_SOAPcsharp.ServiceReference1.AdminService_SOAP)(this)).findAllUsersInfo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sdi3_23.Cli_SOAPcsharp.ServiceReference1.findAllUsersInfoResponse> sdi3_23.Cli_SOAPcsharp.ServiceReference1.AdminService_SOAP.findAllUsersInfoAsync(sdi3_23.Cli_SOAPcsharp.ServiceReference1.findAllUsersInfo request) {
            return base.Channel.findAllUsersInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<sdi3_23.Cli_SOAPcsharp.ServiceReference1.findAllUsersInfoResponse> findAllUsersInfoAsync() {
            sdi3_23.Cli_SOAPcsharp.ServiceReference1.findAllUsersInfo inValue = new sdi3_23.Cli_SOAPcsharp.ServiceReference1.findAllUsersInfo();
            return ((sdi3_23.Cli_SOAPcsharp.ServiceReference1.AdminService_SOAP)(this)).findAllUsersInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sdi3_23.Cli_SOAPcsharp.ServiceReference1.disableUserResponse sdi3_23.Cli_SOAPcsharp.ServiceReference1.AdminService_SOAP.disableUser(sdi3_23.Cli_SOAPcsharp.ServiceReference1.disableUser request) {
            return base.Channel.disableUser(request);
        }
        
        public void disableUser(long arg0) {
            sdi3_23.Cli_SOAPcsharp.ServiceReference1.disableUser inValue = new sdi3_23.Cli_SOAPcsharp.ServiceReference1.disableUser();
            inValue.arg0 = arg0;
            sdi3_23.Cli_SOAPcsharp.ServiceReference1.disableUserResponse retVal = ((sdi3_23.Cli_SOAPcsharp.ServiceReference1.AdminService_SOAP)(this)).disableUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sdi3_23.Cli_SOAPcsharp.ServiceReference1.disableUserResponse> sdi3_23.Cli_SOAPcsharp.ServiceReference1.AdminService_SOAP.disableUserAsync(sdi3_23.Cli_SOAPcsharp.ServiceReference1.disableUser request) {
            return base.Channel.disableUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<sdi3_23.Cli_SOAPcsharp.ServiceReference1.disableUserResponse> disableUserAsync(long arg0) {
            sdi3_23.Cli_SOAPcsharp.ServiceReference1.disableUser inValue = new sdi3_23.Cli_SOAPcsharp.ServiceReference1.disableUser();
            inValue.arg0 = arg0;
            return ((sdi3_23.Cli_SOAPcsharp.ServiceReference1.AdminService_SOAP)(this)).disableUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sdi3_23.Cli_SOAPcsharp.ServiceReference1.findAllUsersResponse sdi3_23.Cli_SOAPcsharp.ServiceReference1.AdminService_SOAP.findAllUsers(sdi3_23.Cli_SOAPcsharp.ServiceReference1.findAllUsers request) {
            return base.Channel.findAllUsers(request);
        }
        
        public sdi3_23.Cli_SOAPcsharp.ServiceReference1.userDTO[] findAllUsers() {
            sdi3_23.Cli_SOAPcsharp.ServiceReference1.findAllUsers inValue = new sdi3_23.Cli_SOAPcsharp.ServiceReference1.findAllUsers();
            sdi3_23.Cli_SOAPcsharp.ServiceReference1.findAllUsersResponse retVal = ((sdi3_23.Cli_SOAPcsharp.ServiceReference1.AdminService_SOAP)(this)).findAllUsers(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sdi3_23.Cli_SOAPcsharp.ServiceReference1.findAllUsersResponse> sdi3_23.Cli_SOAPcsharp.ServiceReference1.AdminService_SOAP.findAllUsersAsync(sdi3_23.Cli_SOAPcsharp.ServiceReference1.findAllUsers request) {
            return base.Channel.findAllUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<sdi3_23.Cli_SOAPcsharp.ServiceReference1.findAllUsersResponse> findAllUsersAsync() {
            sdi3_23.Cli_SOAPcsharp.ServiceReference1.findAllUsers inValue = new sdi3_23.Cli_SOAPcsharp.ServiceReference1.findAllUsers();
            return ((sdi3_23.Cli_SOAPcsharp.ServiceReference1.AdminService_SOAP)(this)).findAllUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sdi3_23.Cli_SOAPcsharp.ServiceReference1.enableUserResponse sdi3_23.Cli_SOAPcsharp.ServiceReference1.AdminService_SOAP.enableUser(sdi3_23.Cli_SOAPcsharp.ServiceReference1.enableUser request) {
            return base.Channel.enableUser(request);
        }
        
        public void enableUser(long arg0) {
            sdi3_23.Cli_SOAPcsharp.ServiceReference1.enableUser inValue = new sdi3_23.Cli_SOAPcsharp.ServiceReference1.enableUser();
            inValue.arg0 = arg0;
            sdi3_23.Cli_SOAPcsharp.ServiceReference1.enableUserResponse retVal = ((sdi3_23.Cli_SOAPcsharp.ServiceReference1.AdminService_SOAP)(this)).enableUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sdi3_23.Cli_SOAPcsharp.ServiceReference1.enableUserResponse> sdi3_23.Cli_SOAPcsharp.ServiceReference1.AdminService_SOAP.enableUserAsync(sdi3_23.Cli_SOAPcsharp.ServiceReference1.enableUser request) {
            return base.Channel.enableUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<sdi3_23.Cli_SOAPcsharp.ServiceReference1.enableUserResponse> enableUserAsync(long arg0) {
            sdi3_23.Cli_SOAPcsharp.ServiceReference1.enableUser inValue = new sdi3_23.Cli_SOAPcsharp.ServiceReference1.enableUser();
            inValue.arg0 = arg0;
            return ((sdi3_23.Cli_SOAPcsharp.ServiceReference1.AdminService_SOAP)(this)).enableUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sdi3_23.Cli_SOAPcsharp.ServiceReference1.findUserByIdResponse sdi3_23.Cli_SOAPcsharp.ServiceReference1.AdminService_SOAP.findUserById(sdi3_23.Cli_SOAPcsharp.ServiceReference1.findUserById request) {
            return base.Channel.findUserById(request);
        }
        
        public sdi3_23.Cli_SOAPcsharp.ServiceReference1.userDTO findUserById(long arg0) {
            sdi3_23.Cli_SOAPcsharp.ServiceReference1.findUserById inValue = new sdi3_23.Cli_SOAPcsharp.ServiceReference1.findUserById();
            inValue.arg0 = arg0;
            sdi3_23.Cli_SOAPcsharp.ServiceReference1.findUserByIdResponse retVal = ((sdi3_23.Cli_SOAPcsharp.ServiceReference1.AdminService_SOAP)(this)).findUserById(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sdi3_23.Cli_SOAPcsharp.ServiceReference1.findUserByIdResponse> sdi3_23.Cli_SOAPcsharp.ServiceReference1.AdminService_SOAP.findUserByIdAsync(sdi3_23.Cli_SOAPcsharp.ServiceReference1.findUserById request) {
            return base.Channel.findUserByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<sdi3_23.Cli_SOAPcsharp.ServiceReference1.findUserByIdResponse> findUserByIdAsync(long arg0) {
            sdi3_23.Cli_SOAPcsharp.ServiceReference1.findUserById inValue = new sdi3_23.Cli_SOAPcsharp.ServiceReference1.findUserById();
            inValue.arg0 = arg0;
            return ((sdi3_23.Cli_SOAPcsharp.ServiceReference1.AdminService_SOAP)(this)).findUserByIdAsync(inValue);
        }
    }
}
